# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 543aaea6ad50e07ac51d5a58e4a0fb93c6f93d0836a10d3bc04c44edc087cc4654ef1e2adf96455542b8de23fd9b2ba60db022f29d005d95eff1877e5595162e

test:
  secret_key_base: 01288239978f1755f47b58e2f3d71636e4be4d87ed3e82cec52b085f485c18d8c3b26d5499807d15b5519b558e9937ab2d229dc7fe59e856705c22864d302b88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
